version: 1
tasks:
  -
    id: task_id
    name: task_name
    URL: https://path-to-csv.csv
    type: csv/xml
    delimiter: ;
    export:
      -
        marketplace: WB
        reset_missing: true
        schema: 
          code: 3
          amount: 9
        active: yes
      -
        marketplace: OZON
        reset_missing: true
        schema: 
          prefix: LM
          code: 1
          amount: 9
        active: yes